apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: platform-controller-claim0
  name: platform-controller-claim0
spec:
  accessModes:
  - ReadWriteOnce 
  resources:
    requests:
      storage: 100Mi
status: {}
