apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.21.0 (992df58d8)
  creationTimestamp: null
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.21.0 (992df58d8)
      creationTimestamp: null
      labels:
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: redis
    spec:
      volumes:
      - name: task-pv-redis
        persistentVolumeClaim:
          claimName: redis-pv-claim
      containers:
      - name: redis
        image: redis:5.0.4
        command: ["redis-server"]
        args: ["/data/redis.conf"]
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /data
          name: task-pv-redis
      
