apiVersion: v1
kind: PersistentVolume
metadata:
  name: keycloak-pv-volume
  labels:
    type: local
spec:
  storageClassName: keycloak
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pv-claim
spec:
  storageClassName: keycloak
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: redis-pv-volume
  labels:
    type: local
spec:
  storageClassName: redis
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data/redis-db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pv-claim
spec:
  storageClassName: redis
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: vos-pv-volume
  labels:
    type: local
spec:
  storageClassName: vos
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/opt/virtuoso-opensource/var/lib/virtuoso/db"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vos-pv-claim
spec:
  storageClassName: vos
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
