apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gui
  name: gui
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    protocol: TCP
  selector:
    io.kompose.service: gui
status:
  loadBalancer: {}
