apiVersion: apps/v1
kind: Deployment
metadata:
  name: platform-controller
  labels:
    app: platform-controller
  annotations:
    "cni.projectcalico.org/ipv4pools": "[\"hobbit-core\"]"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: platform-controller
  template:
    metadata:
      labels:
        app: platform-controller
    spec:
      containers:
      - name: platform-controller
        image: hobbitproject/hobbit-platform-controller:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: HOBBIT_RABBIT_HOST
          value: "rabbit"
        - name: HOBBIT_RABBIT_EXPERIMENTS_HOST
            value: "rabbit"
        - name: HOBBIT_REDIS_HOST
            value: "redis"
        - name: DEPLOY_ENV
            value: "testing"
        - name: GITLAB_USER
            value: "${GITLAB_USER}"
        - name: GITLAB_EMAIL
            value: "${GITLAB_EMAIL}"
        - name: GITLAB_TOKEN
            value: "${GITLAB_TOKEN}"
        - name: SWARM_NODE_NUMBER
            value: "1"
        volumeMounts:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
