apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose -f docker-compose-dev.yml convert --volumes hostPath
    kompose.version: 1.21.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: cadvisor
  name: cadvisor
spec:
  replicas: 1
  selector:
    matchLabels:
    io.kompose.service: cadvisor
  strategy:
    type: Recreate
  template:
    metadata:
    annotations:
        kompose.cmd: kompose -f docker-compose-dev.yml convert --volumes hostPath
        kompose.version: 1.21.0 ()
    creationTimestamp: null
    labels:
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: cadvisor
    spec:
    containers:
    - image: google/cadvisor
        imagePullPolicy: ""
        name: cadvisor
        resources: {}
        volumeMounts:
        - mountPath: /rootfs
        name: cadvisor-hostpath0
        readOnly: true
        - mountPath: /dev/disk
        name: cadvisor-hostpath1
        readOnly: true
        - mountPath: /sys
        name: cadvisor-hostpath2
        readOnly: true
        - mountPath: /var/lib/docker
        name: cadvisor-hostpath3
        readOnly: true
        - mountPath: /var/run
        name: cadvisor-hostpath4
    restartPolicy: Always
    serviceAccountName: ""
    volumes:
    - hostPath:
        path: /
        name: cadvisor-hostpath0
    - hostPath:
        path: /dev/disk
        name: cadvisor-hostpath1
    - hostPath:
        path: /sys
        name: cadvisor-hostpath2
    - hostPath:
        path: /var/lib/docker
        name: cadvisor-hostpath3
    - hostPath:
        path: /var/run
        name: cadvisor-hostpath4
status: {}
