apiVersion: extensions/v1beta1
kind: NetworkPolicy
metadata:
  name: hobbit
  namespace: hobbit
spec:
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - ipBlock:
        cidr: 172.16.100.0/24
    - podSelector:
        matchLabels:
          io.kompose.network/hobbit: "true"
  podSelector:
    matchLabels:
      io.kompose.network/hobbit: "true"
