apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: rabbit
  name: rabbit
  namespace: hobbit
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: rabbit
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hobbit: "true"
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: rabbit
    spec:
      containers:
      - image: rabbitmq:management
        imagePullPolicy: IfNotPresent
        name: rabbit
        ports:
        - containerPort: 15672
        - containerPort: 5672
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
      volumes: null
status: {}
