apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: vos
  name: vos
spec:
  ports:
  - name: "8890"
    port: 8890
    targetPort: 8890
  selector:
    io.kompose.service: vos
status:
  loadBalancer: {}
