# regulating access to jobs and nodes in default namespace
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-reader
  namespace: default
  labels:
    app: tools-rbac
rules:
- apiGroups: ["batch"] # batch is the core API group for jobs resource
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
# This role binding allows any user in the "system:serviceaccounts" group retrieve, list, create and delete jobs  in the default namespace
metadata:
  name: read-jobs
  namespace: default
  labels:
    app: tools-rbac
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
    namespace: default
roleRef:
  kind: Role
  name: jobs-reader
  apiGroup: ""
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: node-cluster-role
rules:
  - apiGroups: [""] # nodes do not have specific apiGroup
    resources: ["nodes"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
# This cluster role binding allows anyone in the "system:serviceaccounts" group to get, list and watch nodes in any namespace.
metadata:
  name: service-account-clusterrolebinding
  labels:
    app: tools-rbac
subjects:
  - kind: Group
    name: system:serviceaccounts
    apiGroup: rbac.authorization.k8s.io
    namespace: default
roleRef:
  kind: ClusterRole
  name: node-cluster-role
  apiGroup: rbac.authorization.k8s.io






