apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-volume-00
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elkdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-volume-01
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elkdata"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: elastic-volume-02
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/elkdata"
