apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: analysis
  name: analysis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: analysis
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: analysis
    spec:
      nodeSelector:
        node-role: system
      containers:
      - env:
        - name: HOBBIT_RABBIT_HOST
          value: 192.168.210.214:5672
        image: hobbitproject/hobbit-analysis-component:latest
        imagePullPolicy: "IfNotPresent"
        name: analysis
        resources: {}
      restartPolicy: Always
      serviceAccountName: ""
