apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gui
  name: gui
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
    nodePort: 30007
  selector:
    io.kompose.service: gui
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gui
  name: gui
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: gui
  strategy: {}
  template:
    metadata:
      labels:
        io.kompose.network/hobbit: "true"
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: gui
    spec:
      hostNetwork: true
      nodeSelector:
        node-role: system
      containers:
      - env:
        - name: CHECK_REALM_URL
          value: "false"
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_HTTP_PORT
          value: "9200"
        - name: HOBBIT_RABBIT_HOST
          value: 192.168.210.214
        - name: KEYCLOAK_AUTH_URL
          value: "http://131.234.28.241:31058/auth"
        - name: KEYCLOAK_DIRECT_URL
          value: "http://131.234.28.241:31058/auth"
        image: oluoniyide/hobbit-gui:1.0.5
        imagePullPolicy: ""
        name: gui
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
