apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
  labels:
    io.kompose.service: logstash
  name: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: logstash
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.22.0 (955b78124)
      creationTimestamp: null
      labels:
        io.kompose.network/hobbit: "true"
        io.kompose.network/hobbit-core: "true"
        io.kompose.network/hobbit-services: "true"
        io.kompose.service: logstash
    spec:
      containers:
        - args:
            - logstash
            - -f
            - /usr/share/logstash/config/logstash.conf
          env:
            - name: LS_JAVA_OPTS
              value: -Xmx256m -Xms256m
            - name: constraint:org.hobbit.type
              value: =data
          image: docker.elastic.co/logstash/logstash:5.2.2
          name: logstash
          ports:
            - containerPort: 12201
            - containerPort: 12201
              protocol: UDP
          resources: {}
          volumeMounts:
            - mountPath: /usr/share/logstash/config/logstash.conf
              name: logstash-claim0
              readOnly: true
            - mountPath: /usr/share/logstash/config/logstash.yml
              name: logstash-claim1
              readOnly: true
      restartPolicy: Always
      volumes:
        - name: logstash-claim0
          persistentVolumeClaim:
            claimName: logstash-claim0
            readOnly: true
        - name: logstash-claim1
          persistentVolumeClaim:
            claimName: logstash-claim1
            readOnly: true
status: {}
