apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: platform-controller
  name: platform-controller
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: platform-controller
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: platform-controller
    spec:
      hostname: platform-controller
      nodeSelector:
        node-role: benchmark
      containers:
      - env:
        - name: DEPLOY_ENV
          value: testing
        - name: GITLAB_USER
          value: ""
        - name: GITLAB_EMAIL
          value: ""
        - name: GITLAB_TOKEN
          value: ""
        - name: HOBBIT_RABBIT_IMAGE
          value: "rabbitmq:management"
        - name: HOBBIT_RABBIT_HOST
          value: rabbit.default.svc.cluster.local:5672
        - name: HOBBIT_REDIS_HOST
          value: redis.default.svc.cluster.local
        - name: SWARM_NODE_NUMBER
          value: "1"
        image: oluoniyide/platformcontroller:3.2.1
        imagePullPolicy: ""
        name: platform-controller
      restartPolicy: Always
      serviceAccountName: ""
