apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  ports:
  - name: "6379"
    port: 6379
    targetPort: 6379
    nodePort: 31062
  selector:
    io.kompose.service: redis
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: redis
  name: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: redis
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.network/hobbit-core: "true"
        io.kompose.service: redis
    spec:
      hostname: redis
      nodeSelector:
        node-role: system
      volumes:
      - name: task-pv-redis
        persistentVolumeClaim:
          claimName: redis-pv-claim
      containers:
      - name: redis
        image: redis:5.0.4
        command: ["redis-server"]
        args: ["/data/redis.conf"]
        env:
        - name: MASTER
          value: "true"
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "0.1"
        volumeMounts:
        - mountPath: /data
          name: task-pv-redis

