apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: jobs-reader
  namespace: default
  labels:
    app: tools-rbac
rules:
- apiGroups: ["batch"]
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create", "delete"]
- apiGroups: [""]
  resources: ["nodes"]
  verbs: ["get", "watch", "list"]





