apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-jobs
  namespace: default
  labels:
    app: tools-rbac
  namespace: default
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: default
roleRef:
  kind: Role
  name: jobs-reader
  apiGroup: ""
